### ISSUE TITLE
Copyedit Fragments

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/caravans-wax#4]
The markdown files in the `_fragments` directory contain YAML front-matter that populates the tables on collection item pages. Here's the [collection](http://caravans.blockmuseum.northwestern.edu.s3-website-us-east-1.amazonaws.com/collection/) and here's a collection item [page](http://caravans.blockmuseum.northwestern.edu.s3-website-us-east-1.amazonaws.com/fragments/1/).

### The problem
The written content for the pages were programmatically generated by a script that pulled data from a spreadsheet. There are punctuation errors and nonsensical characters in the YAML front-matter that were introduced by the process.

- Each row in the spreadsheet represents an `.md` file in the `_fragments` directory
- The `Img. No.` in the spreadsheet maps to the filename of the markdown file and the `pid` field in the YAML front-matter

### To Do
- Review [the spreadsheet](https://docs.google.com/spreadsheets/d/11HdK3seLNmrFsVChYIqopfp3SU1WeC283uLlIZO5GFU/edit?usp=sharing) and make sure the content is accurately represented in the corresponding `.md` file in the `_fragments` directory.
- Review the HTML rendering of the `.md` file on the [website](http://caravans.blockmuseum.northwestern.edu.s3-website-us-east-1.amazonaws.com/collection/) or locally and correct any obvious spelling, formatting, or grammar issues.

### Done looks like
All errors are corrected in a new branch and a PR is submitted.

**Comment by echoe320** [comment]
solved in #9
